version: '2.0'

services:

  simu:
    build:
      context: .
      dockerfile: Dockerfile.simu
    container_name: fortrants_simu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - results:/results/

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserv
    container_name: fortrants_webserv
    expose:
      - 5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - results:/results/

volumes:
  results:
