version: '2.0'

services:

  simu:
    build:
      context: .
      dockerfile: Dockerfile.simu
    container_name: fortrants_simu
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - results:/results/

  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserv
    container_name: fortrants_webserv
    expose:
      - 80
    volumes:
      - ./webserver/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./webserver/www:/var/www:ro
      - ./webserver/www-cgi:/var/www-cgi:ro
      - results:/var/www-results:ro

volumes:
  results:
